dist: trusty
sudo: false
language: cpp
compiler:
  - clang
cache: apt

addons:
  apt:
    packages:
    - cmake
    - libffms2-dev
    - libgflags-dev
    - libgoogle-glog-dev
    - libmicrohttpd-dev
    - libprotobuf-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
    - libstdc++-4.8-dev
    - libusb-1.0-0-dev
    - ninja-build

script:
  - ./build/travis.sh
